name: iremibreathingapp
description: App against Anxiety that gives breathing exercises

publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.0
  sqflite: ^2.2.6
  intl: ^0.18.0
  flutter_staggered_grid_view: ^0.6.2
  provider: ^6.0.5
  path_provider: ^2.0.14
  file_picker: ^5.2.10
  achievement_view: ^1.0.1
  syncfusion_flutter_charts: ^21.1.37
  flutter_tts: ^3.6.3
  permission_handler: ^10.2.0
  flutter_native_splash: ^2.2.19
  shared_preferences: ^2.0.20

# ON CHANGE: flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#01B3CA"
  image: "assets/icon/icon.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icon/icon.png
